version: "3.9"  # optional since v1.27.0
services:
  web_api:
    build: . 
    container_name: web_api_application
    ports:
      - "5000:80"
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - 1433:1433 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports: 
    - 25672:25672
    - 15672:15672 
    - '5672:5672'
    restart: always